
# Copyright (c) 2022 Espresso Systems (espressosys.com)
# This file is part of the Espresso library.
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU
# General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program. If not,
# see <https://www.gnu.org/licenses/>.

# TOML file for node configuration.

title = "Node Configuration"

# Seed number used to generate secret key set for all nodes
seed = [1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8]

num_bootstrap = 7
replication_factor = 5

mesh_n_high = 15
mesh_n_low = 8
mesh_outbound_min = 4
mesh_n = 12

bootstrap_mesh_n_high = 50
bootstrap_mesh_n_low = 10
bootstrap_mesh_outbound_min = 5
bootstrap_mesh_n = 15

# Bootstrap node information
[[nodes]]
ip = "127.0.0.1"
port = 9100

[[nodes]]
ip = "127.0.0.1"
port = 9101

[[nodes]]
ip = "127.0.0.1"
port = 9102

[[nodes]]
ip = "127.0.0.1"
port = 9103

[[nodes]]
ip = "127.0.0.1"
port = 9104

[[nodes]]
ip = "127.0.0.1"
port = 9105

[[nodes]]
ip = "127.0.0.1"
port = 9106
