[workspace]
resolver = "2"

members = [
	"address-book",
    "examples/asynctide",
    "examples/tideui",
    "faucet",
    "validator",
    "zerok/apis/availability",
    "zerok/apis/catchup",
    "zerok/apis/metastate",
    "zerok/apis/status",
    "zerok/zerok_client",
    "zerok/zerok_lib",
    "zerok/zerok_validator",
    ]
[profile.dev]
opt-level = 1
[profile.release]
debug = true
# lto = "thin"
