# Copyright (c) 2022 Espresso Systems (espressosys.com)
# This file is part of the Espresso library.
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU
# General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program. If not,
# see <https://www.gnu.org/licenses/>.

[meta]
FORMAT_VERSION = "0.1.0"

[route.check_nullifier]
PATH = ["/check_nullifier/:block_id/:nullifier"]
":block_id" = "Integer"
":nullifier" = "TaggedBase64"
DOC = """
Get a proof that a nullifier was spent or unspent after a given block.

Returns
```
{
	"spent": bool
	"proof": SetMerkleProof
}
```

`spent` indicates whether the given nullifier was spent after the block with the given index (block
0 being the genesis block). `proof` authenticates the spent/unspent status relative to the nullifier
set root hash in the state after `block_id`.
"""
