# Copyright (c) 2022 Espresso Systems (espressosys.com)
# This file is part of the Espresso library.
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU
# General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program. If not,
# see <https://www.gnu.org/licenses/>.

[meta]
NAME = "espresso-status"
DESCRIPTION = "Snapshots of consensus related state"
FORMAT_VERSION = "0.1.0"

[route.list_peers]
PATH = ["/list_peers"]
DOC = """
List peers connected to this node.

Returns an array of `PeerInfo`. Each `PeerInfo` has the schema
```
{
	"peer_id": "PubKey"
}
```
"""

[route.latest_block_id]
PATH = ["/latest_block_id"]
DOC = """
Get the ID (block number) of the latest committed block.
"""

[route.mempool_info]
PATH = ["/mempool_info"]
DOC = """
Get information about the mempool.

Returns 
```
{
	"transaction_count": "integer",
	"output_count": "integer",
	"memory_footprint": "integer",
}
```
"""

[route.success_rate]
PATH = ["/success_rate"]
DOC = """
Get the block success rate.

Returns the fraction of proposed blocks which have been committed, as a floating point number.
"""

[route.throughput]
PATH = ["/throughput"]
DOC = """
Get the data needed to calculate throughput in blocks, transactions, and bytes.

Returns
```
{
	"blocks_finalized": "integer",
	"transactions_finalized": "integer",
	"bytes_finalized": "integer",
	"time_operational": "duration"
}
```
"""

[route.location]
PATH = ["/location"]
DOC = """
Get the location of this node.

Returns
```
{
	"location": "String"
}
```
"""
